from __future__ import annotations

import json

import pandas as pd
import pytest
from typer.testing import CliRunner

from statconvert.backends.arrow_backend import ArrowBackend
from statconvert.cli import app
from statconvert.dataset import Dataset
from statconvert.exceptions import OutputPathError
from statconvert.metadata import DatasetMetadata, VariableMetadata
from statconvert.metadata.scripts import (
    export_metadata_script,
    render_r_script,
    render_spss_script,
    render_stata_script,
)


runner = CliRunner()


def _script_dataset(*, dataset_label: str = "Study dataset") -> Dataset:
    metadata = DatasetMetadata(
        source_format="sav",
        source_backend="pyreadstat",
        dataset_label=dataset_label,
        notes=["Owner's review."],
    )
    metadata.add_variable(
        VariableMetadata(
            name="status",
            label='Patient "status"',
            value_labels={2: "Inactive", 1: "Active"},
            missing_values=[-99],
            display_format="F8.0",
            measure="nominal",
            storage_type="float64",
        )
    )
    metadata.add_variable(
        VariableMetadata(
            name="visit date",
            label="Visit date",
            missing_ranges=[{"low": 90, "high": 99}],
            display_format="DATE11",
            measure="scale",
            storage_type="datetime64[ns]",
        )
    )
    return Dataset(
        dataframe=pd.DataFrame(
            {
                "status": [1.0, 2.0],
                "visit date": pd.to_datetime(["2026-01-01", "2026-01-02"]),
            }
        ),
        source_format="sav",
        source_file="survey.sav",
        normalized_metadata=metadata,
        metadata_provenance={
            "dataset": "automatic_sidecar",
            "columns": {
                "status": "automatic_sidecar",
                "visit date": "automatic_sidecar",
            },
        },
    )


def _single_column_dataset(*, label: str, provenance: str) -> Dataset:
    metadata = DatasetMetadata(
        source_format="sav",
        dataset_label=label,
        notes=["Resolved"],
    )
    metadata.add_variable(
        VariableMetadata(
            name="status",
            label=f"{label} status",
            value_labels={1: "Active"},
            storage_type="int64",
        )
    )
    return Dataset(
        dataframe=pd.DataFrame({"status": [1]}),
        source_format="sav",
        normalized_metadata=metadata,
        metadata_provenance={
            "dataset": provenance,
            "columns": {"status": provenance},
        },
    )


def test_r_script_is_deterministic_and_uses_safe_base_r_attributes():
    dataset = _script_dataset()

    script = render_r_script(dataset, "survey.sav")

    assert script == render_r_script(dataset, "survey.sav")
    assert "# Generated by StatConvert" in script
    assert "# Resolved metadata source: automatic_sidecar" in script
    assert "review before running" in script
    assert 'attr(df, "label") <- "Study dataset"' in script
    assert 'attr(df, "notes") <- c("Owner\'s review.")' in script
    assert 'df[["visit date"]]' in script
    assert (
        'attr(df[["status"]], "label") <- "Patient \\"status\\""' in script
    )
    assert (
        'attr(df[["status"]], "labels") <- '
        'c("Active" = 1, "Inactive" = 2)' in script
    )
    assert "Unsupported or review-required metadata" in script
    assert "user-defined missing metadata" in script
    assert "measurement level" in script
    assert "display format" in script


def test_stata_script_emits_safe_labels_and_comments_invalid_names():
    script = render_stata_script(_script_dataset(), "survey.sav")

    assert "* Generated by StatConvert" in script
    assert 'label data `"Study dataset"\'' in script
    assert 'notes: `"Owner\'s review."\'' in script
    assert 'label variable status `"Patient "status""\'' in script
    assert (
        'label define scvl_1_status 1 `"Active"\' 2 `"Inactive"\', replace'
        in script
    )
    assert "label values status scvl_1_status" in script
    assert "visit date: invalid Stata variable name" in script
    assert "user-defined missing metadata requires manual review" in script
    assert "measurement level 'nominal'" in script
    assert "format status F8.0" not in script


def test_spss_script_emits_safe_supported_commands_and_review_comments():
    script = render_spss_script(_script_dataset(), "survey.sav")

    assert "* Generated by StatConvert." in script
    assert "* Source dataset: survey(dot)sav." in script
    assert "VARIABLE LABELS status 'Patient \"status\"'." in script
    assert "VALUE LABELS status" in script
    assert "  1 'Active'" in script
    assert "  2 'Inactive'" in script
    assert "MISSING VALUES status (-99)." in script
    assert "VARIABLE LEVEL status (NOMINAL)." in script
    assert "FORMATS status (F8.0)." in script
    assert "visit date: invalid SPSS variable name" in script
    assert "Dataset label: Study dataset" in script
    assert "Dataset note: Owner's review(dot)" in script
    assert "Unsupported or review-required metadata" in script


def test_metadata_cli_writes_all_supported_script_targets(tmp_path):
    source = tmp_path / "plain.csv"
    pd.DataFrame({"status": [1]}).to_csv(source, index=False)
    _single_column_dataset(
        label="Sidecar survey",
        provenance="explicit_sidecar",
    ).write_sidecar(source)

    for filename, expected in (
        ("labels.R", 'attr(df[["status"]], "label")'),
        ("labels.do", "label variable status"),
        ("labels.sps", "VARIABLE LABELS status"),
    ):
        target = tmp_path / filename
        result = runner.invoke(
            app,
            ["metadata", str(source), "--export-script", str(target)],
        )
        assert result.exit_code == 0
        assert "Metadata helper script written" in result.output
        text = target.read_text(encoding="utf-8")
        assert expected in text
        assert "Resolved metadata source: automatic_sidecar" in text


def test_script_export_uses_embedded_arrow_and_sidecar_precedence(tmp_path):
    source = tmp_path / "metadata.parquet"
    embedded_target = tmp_path / "embedded.R"
    sidecar_target = tmp_path / "sidecar.R"
    ArrowBackend().write(
        _single_column_dataset(
            label="Embedded survey",
            provenance="embedded_arrow",
        ),
        source,
    )
    sidecar = Dataset.sidecar_path(source)
    payload = json.loads(sidecar.read_text(encoding="utf-8"))
    sidecar.unlink()

    embedded = runner.invoke(
        app,
        [
            "metadata",
            str(source),
            "--export-script",
            str(embedded_target),
        ],
    )
    payload["dataset_metadata"]["dataset_label"] = "Sidecar wins"
    payload["columns"][0]["label"] = "Winning label"
    sidecar.write_text(json.dumps(payload), encoding="utf-8")
    sidecar_result = runner.invoke(
        app,
        [
            "metadata",
            str(source),
            "--export-script",
            str(sidecar_target),
        ],
    )

    embedded_text = embedded_target.read_text(encoding="utf-8")
    sidecar_text = sidecar_target.read_text(encoding="utf-8")
    assert embedded.exit_code == sidecar_result.exit_code == 0
    assert "Resolved metadata source: embedded_arrow" in embedded_text
    assert '"Embedded survey"' in embedded_text
    assert "Resolved metadata source: automatic_sidecar" in sidecar_text
    assert '"Sidecar wins"' in sidecar_text
    assert '"Winning label"' in sidecar_text


def test_script_output_safety_and_option_validation(tmp_path):
    source = tmp_path / "plain.csv"
    target = tmp_path / "labels.R"
    pd.DataFrame({"status": [1]}).to_csv(source, index=False)
    command = [
        "metadata",
        str(source),
        "--export-script",
        str(target),
    ]
    assert runner.invoke(app, command).exit_code == 0

    collision = runner.invoke(app, command)
    overwritten = runner.invoke(app, [*command, "--overwrite-script"])
    missing_parent = runner.invoke(
        app,
        [
            "metadata",
            str(source),
            "--export-script",
            str(tmp_path / "missing" / "labels.R"),
        ],
    )
    unsupported = runner.invoke(
        app,
        [
            "metadata",
            str(source),
            "--export-script",
            str(tmp_path / "labels.txt"),
        ],
    )
    overwrite_only = runner.invoke(
        app,
        ["metadata", str(source), "--overwrite-script"],
    )

    assert collision.exit_code == 1
    assert "Metadata helper script already exists" in collision.output
    assert "Use --overwrite-script" in collision.output
    assert overwritten.exit_code == 0
    assert missing_parent.exit_code == 1
    assert "Parent folder does not exist" in missing_parent.output
    assert "Create the folder first" in missing_parent.output
    assert unsupported.exit_code == 1
    assert "Unsupported script output format: .txt" in unsupported.output
    assert "Use .R, .do, or .sps" in unsupported.output
    assert overwrite_only.exit_code == 1
    assert "--overwrite-script requires --export-script" in overwrite_only.output


def test_script_path_cannot_replace_input(tmp_path):
    source = tmp_path / "source.R"
    source.write_text("unchanged\n", encoding="utf-8")

    with pytest.raises(OutputPathError, match="would replace the input file"):
        export_metadata_script(Dataset(pd.DataFrame({"id": [1]})), source, source)

    assert source.read_text(encoding="utf-8") == "unchanged\n"


def test_selected_workbook_script_works_and_ambiguous_input_fails(tmp_path):
    source = tmp_path / "book.xlsx"
    target = tmp_path / "selected.R"
    with pd.ExcelWriter(source, engine="xlsxwriter") as workbook:
        pd.DataFrame({"id": [1]}).to_excel(
            workbook,
            sheet_name="Data",
            index=False,
        )
        pd.DataFrame({"code": ["A"]}).to_excel(
            workbook,
            sheet_name="Lookup",
            index=False,
        )

    selected = runner.invoke(
        app,
        [
            "metadata",
            str(source),
            "--object",
            "Data",
            "--export-script",
            str(target),
        ],
    )
    ambiguous_target = tmp_path / "ambiguous.R"
    ambiguous = runner.invoke(
        app,
        [
            "metadata",
            str(source),
            "--export-script",
            str(ambiguous_target),
        ],
    )

    assert selected.exit_code == 0
    assert 'df[["id"]]' not in target.read_text(encoding="utf-8")
    assert ambiguous.exit_code == 1
    assert not ambiguous_target.exists()


def test_script_options_exist_only_on_metadata_command():
    help_result = runner.invoke(app, ["metadata", "--help"])
    assert help_result.exit_code == 0
    assert "--export-script" in help_result.output
    assert "--overwrite-script" in help_result.output

    for command in ("convert", "batch", "transform"):
        result = runner.invoke(app, [command, "--help"])
        assert result.exit_code == 0
        assert "--export-script" not in result.output
        assert "--overwrite-script" not in result.output
