from __future__ import annotations

import copy
import json
from pathlib import Path
import tomllib

import pandas as pd
import pytest
from typer.testing import CliRunner

from statconvert.backends.arrow_backend import ArrowBackend
from statconvert.cli import app
from statconvert.contracts import (
    build_schema_contract,
    contract_to_toml,
    export_schema_contract,
    load_contract,
    validate_contract,
)
from statconvert.dataset import ColumnMetadata, Dataset
from statconvert.exceptions import ContractError, OutputPathError
from statconvert.metadata import DatasetMetadata, VariableMetadata


runner = CliRunner()


def test_build_exported_contract_uses_conservative_defaults() -> None:
    dataset = Dataset(
        pd.DataFrame(
            {
                "id": [1, 2],
                "optional": ["value", None],
            }
        )
    )

    contract = build_schema_contract(dataset, "people.csv")

    assert contract.contract_version == 1
    assert contract.name == "people schema contract"
    assert contract.description == (
        "Generated by StatConvert from resolved dataset schema and metadata."
    )
    assert contract.dataset.require_columns is True
    assert contract.dataset.allow_extra_columns is False
    assert contract.dataset.column_order == "ignore"
    assert [column.name for column in contract.columns] == ["id", "optional"]
    assert contract.columns[0].storage_type == "int64"
    assert contract.columns[0].logical_type == "integer"
    assert contract.columns[0].nullable is False
    assert contract.columns[1].logical_type == "string"
    assert contract.columns[1].nullable is True
    assert all(column.required for column in contract.columns)
    assert all(column.allowed_values is None for column in contract.columns)
    assert all(column.min_value is None for column in contract.columns)
    assert all(column.max_value is None for column in contract.columns)
    assert all(column.regex is None for column in contract.columns)
    assert all(column.unique is False for column in contract.columns)


def test_contract_toml_is_deterministic_and_round_trips() -> None:
    dataset = Dataset(pd.DataFrame({"id": [1], "name": ["Ada"]}))
    contract = build_schema_contract(dataset, "people.csv")

    first = contract_to_toml(contract)
    second = contract_to_toml(contract)
    parsed = tomllib.loads(first)

    assert first == second
    assert parsed["contract_version"] == 1
    assert parsed["dataset"] == {
        "require_columns": True,
        "allow_extra_columns": False,
        "column_order": "ignore",
    }
    assert [column["name"] for column in parsed["columns"]] == ["id", "name"]
    assert "unique" not in first
    assert "allowed_values" not in first
    assert "\nmin =" not in first
    assert "\nmax =" not in first
    assert "\nregex =" not in first


def test_exported_contract_parses_and_validates_source_dataset(
    tmp_path: Path,
) -> None:
    dataset = Dataset(
        pd.DataFrame(
            {
                "id": [1, 2],
                "name": ["Ada", "Grace"],
            }
        )
    )
    source = tmp_path / "people.csv"
    output = tmp_path / "people.toml"

    written = export_schema_contract(dataset, source, output)
    contract = load_contract(written)
    result = validate_contract(dataset, contract)

    assert written == output
    assert result.valid is True
    assert output.read_text(encoding="utf-8").startswith(
        'contract_version = 1\nname = "people schema contract"\n'
    )


def test_contract_build_does_not_modify_dataset() -> None:
    dataset = _resolved_dataset()
    dataframe_before = dataset.dataframe.copy(deep=True)
    metadata_before = copy.deepcopy(dataset.normalized_metadata)
    columns_before = copy.deepcopy(dataset.column_metadata)

    build_schema_contract(dataset, "source.csv")

    pd.testing.assert_frame_equal(dataset.dataframe, dataframe_before)
    assert dataset.normalized_metadata == metadata_before
    assert dataset.column_metadata == columns_before


def test_export_collision_requires_overwrite_contract(
    tmp_path: Path,
) -> None:
    dataset = Dataset(pd.DataFrame({"id": [1]}))
    source = tmp_path / "data.csv"
    output = tmp_path / "schema.toml"
    output.write_text("old", encoding="utf-8")

    with pytest.raises(
        OutputPathError,
        match="Schema contract already exists",
    ):
        export_schema_contract(dataset, source, output)

    export_schema_contract(dataset, source, output, overwrite=True)
    assert load_contract(output).columns[0].name == "id"


def test_export_rejects_missing_parent(tmp_path: Path) -> None:
    with pytest.raises(OutputPathError, match="Parent folder does not exist"):
        export_schema_contract(
            Dataset(pd.DataFrame({"id": [1]})),
            tmp_path / "data.csv",
            tmp_path / "missing" / "schema.toml",
        )


def test_export_rejects_input_path_as_output(tmp_path: Path) -> None:
    path = tmp_path / "data.toml"

    with pytest.raises(
        OutputPathError,
        match="would replace the input file",
    ):
        export_schema_contract(
            Dataset(pd.DataFrame({"id": [1]})),
            path,
            path,
        )


def test_export_rejects_unsupported_extension(tmp_path: Path) -> None:
    with pytest.raises(
        ContractError,
        match="Unsupported schema contract format: .json",
    ):
        export_schema_contract(
            Dataset(pd.DataFrame({"id": [1]})),
            tmp_path / "data.csv",
            tmp_path / "schema.json",
        )


def test_schema_command_exports_contract_and_preserves_schema_output(
    tmp_path: Path,
) -> None:
    source = _write_csv(tmp_path)
    output = tmp_path / "schema.toml"

    result = runner.invoke(
        app,
        [
            "schema",
            str(source),
            "--export-contract",
            str(output),
        ],
    )

    assert result.exit_code == 0
    assert "Schema" in result.output
    assert "Schema contract written:" in result.output
    assert output.name in result.output
    assert load_contract(output).contract_version == 1


def test_schema_command_without_export_remains_display_only(
    tmp_path: Path,
) -> None:
    source = _write_csv(tmp_path)

    result = runner.invoke(app, ["schema", str(source)])

    assert result.exit_code == 0
    assert "Schema" in result.output
    assert "Schema contract written" not in result.output
    assert list(tmp_path.glob("*.toml")) == []


def test_schema_command_collision_and_overwrite(tmp_path: Path) -> None:
    source = _write_csv(tmp_path)
    output = tmp_path / "schema.toml"
    command = [
        "schema",
        str(source),
        "--export-contract",
        str(output),
    ]

    assert runner.invoke(app, command).exit_code == 0
    collision = runner.invoke(app, command)
    overwritten = runner.invoke(app, [*command, "--overwrite-contract"])

    assert collision.exit_code == 1
    assert "Schema contract already exists" in collision.output
    assert "Use --overwrite-contract" in collision.output
    assert overwritten.exit_code == 0


def test_overwrite_contract_requires_export_contract(tmp_path: Path) -> None:
    source = _write_csv(tmp_path)

    result = runner.invoke(
        app,
        ["schema", str(source), "--overwrite-contract"],
    )

    assert result.exit_code == 1
    assert "--overwrite-contract requires --export-contract" in result.output


def test_schema_command_rejects_unsupported_contract_extension(
    tmp_path: Path,
) -> None:
    source = _write_csv(tmp_path)

    result = runner.invoke(
        app,
        [
            "schema",
            str(source),
            "--export-contract",
            str(tmp_path / "schema.json"),
        ],
    )

    assert result.exit_code == 1
    assert "Unsupported schema contract format: .json" in result.output
    assert "Use .toml" in result.output


def test_schema_command_rejects_missing_contract_parent(
    tmp_path: Path,
) -> None:
    source = _write_csv(tmp_path)

    result = runner.invoke(
        app,
        [
            "schema",
            str(source),
            "--export-contract",
            str(tmp_path / "missing" / "schema.toml"),
        ],
    )

    assert result.exit_code == 1
    assert "Parent folder does not exist" in result.output
    assert not (tmp_path / "missing").exists()


def test_schema_command_help_owns_contract_options() -> None:
    schema_help = runner.invoke(app, ["schema", "--help"])
    validate_help = runner.invoke(app, ["validate", "--help"])
    metadata_help = runner.invoke(app, ["metadata", "--help"])

    assert schema_help.exit_code == 0
    assert "--export-contract" in schema_help.output
    assert "--overwrite-contract" in schema_help.output
    assert "--schema-contract" in validate_help.output
    assert "--export-contract" not in metadata_help.output


def test_selected_workbook_object_exports_selected_schema(
    tmp_path: Path,
) -> None:
    workbook = tmp_path / "book.xlsx"
    output = tmp_path / "data.toml"
    with pd.ExcelWriter(workbook) as writer:
        pd.DataFrame({"DataId": [1]}).to_excel(
            writer,
            sheet_name="Data",
            index=False,
        )
        pd.DataFrame({"LookupCode": ["A"]}).to_excel(
            writer,
            sheet_name="Lookup",
            index=False,
        )

    result = runner.invoke(
        app,
        [
            "schema",
            str(workbook),
            "--object",
            "Data",
            "--export-contract",
            str(output),
        ],
    )

    assert result.exit_code == 0
    assert [column.name for column in load_contract(output).columns] == [
        "DataId"
    ]


def test_ambiguous_workbook_does_not_export_contract(
    tmp_path: Path,
) -> None:
    workbook = tmp_path / "book.xlsx"
    output = tmp_path / "schema.toml"
    with pd.ExcelWriter(workbook) as writer:
        pd.DataFrame({"DataId": [1]}).to_excel(
            writer,
            sheet_name="Data",
            index=False,
        )
        pd.DataFrame({"LookupCode": ["A"]}).to_excel(
            writer,
            sheet_name="Lookup",
            index=False,
        )

    result = runner.invoke(
        app,
        [
            "schema",
            str(workbook),
            "--export-contract",
            str(output),
        ],
    )

    assert result.exit_code == 1
    assert "multiple sheets" in result.output
    assert not output.exists()


def test_csv_active_sidecar_supplies_resolved_export_types(
    tmp_path: Path,
) -> None:
    source = _write_csv(tmp_path)
    _resolved_dataset().write_sidecar(source)
    output = tmp_path / "sidecar.toml"

    result = runner.invoke(
        app,
        [
            "schema",
            str(source),
            "--export-contract",
            str(output),
        ],
    )

    contract = load_contract(output)
    assert result.exit_code == 0
    assert contract.columns[0].storage_type == "int32"
    assert contract.columns[0].logical_type == "identifier"


def test_embedded_parquet_supplies_resolved_export_types(
    tmp_path: Path,
) -> None:
    source = tmp_path / "embedded.parquet"
    output = tmp_path / "embedded.toml"
    ArrowBackend().write(_resolved_dataset(), source)
    Dataset.sidecar_path(source).unlink()

    result = runner.invoke(
        app,
        [
            "schema",
            str(source),
            "--export-contract",
            str(output),
        ],
    )

    contract = load_contract(output)
    assert result.exit_code == 0
    assert contract.columns[0].storage_type == "int32"
    assert contract.columns[0].logical_type == "identifier"


def test_sidecar_wins_over_embedded_parquet_export_types(
    tmp_path: Path,
) -> None:
    source = tmp_path / "precedence.parquet"
    output = tmp_path / "precedence.toml"
    ArrowBackend().write(_resolved_dataset(), source)
    sidecar = Dataset.sidecar_path(source)
    payload = json.loads(sidecar.read_text(encoding="utf-8"))
    payload["columns"][0]["physical_type"] = "int16"
    payload["columns"][0]["logical_type"] = "sidecar_identifier"
    sidecar.write_text(json.dumps(payload), encoding="utf-8")

    result = runner.invoke(
        app,
        [
            "schema",
            str(source),
            "--export-contract",
            str(output),
        ],
    )

    contract = load_contract(output)
    assert result.exit_code == 0
    assert contract.columns[0].storage_type == "int16"
    assert contract.columns[0].logical_type == "sidecar_identifier"


def _write_csv(tmp_path: Path) -> Path:
    source = tmp_path / "people.csv"
    pd.DataFrame(
        {
            "id": [1, 2],
            "status": ["active", "inactive"],
        }
    ).to_csv(source, index=False)
    return source


def _resolved_dataset() -> Dataset:
    metadata = DatasetMetadata(
        source_format="sav",
        source_backend="pyreadstat",
    )
    metadata.add_variable(
        VariableMetadata(
            name="id",
            storage_type="int32",
        )
    )
    metadata.add_variable(
        VariableMetadata(
            name="status",
            storage_type="string",
        )
    )
    return Dataset(
        dataframe=pd.DataFrame(
            {
                "id": [1, 2],
                "status": ["active", "inactive"],
            }
        ),
        source_format="sav",
        normalized_metadata=metadata,
        column_metadata={
            "id": ColumnMetadata(
                name="id",
                physical_type="int32",
                logical_type="identifier",
            ),
            "status": ColumnMetadata(
                name="status",
                physical_type="string",
                logical_type="string",
            ),
        },
    )
