from __future__ import annotations

import json
from pathlib import Path
import tomllib
from typing import Any

from statconvert.dataset import Dataset
from statconvert.exceptions import ContractError, OutputPathError

from .model import ColumnContract, DatasetContract, SchemaContract
from .parser import CONTRACT_VERSION, parse_contract
from .schema import resolved_logical_type
from .validator import validate_contract


CONTRACT_EXTENSIONS = (".toml",)
_DESCRIPTION = (
    "Generated by StatConvert from resolved dataset schema and metadata."
)


def build_schema_contract(
    dataset: Dataset,
    input_filename: str | Path | None = None,
) -> SchemaContract:
    """Build a conservative starter contract from one resolved Dataset."""

    source = input_filename or dataset.source_file or "dataset"
    stem = Path(source).stem.strip() or "dataset"
    storage_types = dataset.storage_types()
    columns: list[ColumnContract] = []

    for index, dataframe_column in enumerate(dataset.dataframe.columns):
        name = str(dataframe_column)
        series = dataset.dataframe.iloc[:, index]
        storage_type = _optional_text(storage_types.get(name))
        logical_type = resolved_logical_type(dataset, name, series)
        columns.append(
            ColumnContract(
                name=name,
                required=True,
                storage_type=storage_type,
                logical_type=_optional_text(logical_type),
                nullable=bool(series.isna().any()),
            )
        )

    contract = SchemaContract(
        contract_version=CONTRACT_VERSION,
        name=f"{stem} schema contract",
        description=_DESCRIPTION,
        dataset=DatasetContract(
            require_columns=True,
            allow_extra_columns=False,
            column_order="ignore",
        ),
        columns=tuple(columns),
    )
    result = validate_contract(dataset, contract)
    if not result.valid:
        codes = ", ".join(
            issue.code
            for issue in result.issues
            if issue.severity == "error"
        )
        raise ContractError(
            "Generated schema contract did not validate against the source "
            f"dataset: {codes}."
        )
    return contract


def contract_to_toml(contract: SchemaContract) -> str:
    """Serialize one validated contract using stable TOML field ordering."""

    model = parse_contract(contract.to_dict())
    lines = [
        f"contract_version = {model.contract_version}",
    ]
    if model.name is not None:
        lines.append(f"name = {_format_value(model.name)}")
    if model.description is not None:
        lines.append(f"description = {_format_value(model.description)}")

    lines.extend(
        [
            "",
            "[dataset]",
            f"require_columns = {_format_value(model.dataset.require_columns)}",
            (
                "allow_extra_columns = "
                f"{_format_value(model.dataset.allow_extra_columns)}"
            ),
            f"column_order = {_format_value(model.dataset.column_order)}",
        ]
    )

    for column in model.columns:
        lines.extend(
            [
                "",
                "[[columns]]",
                f"name = {_format_value(column.name)}",
                f"required = {_format_value(column.required)}",
            ]
        )
        if column.storage_type is not None:
            lines.append(
                f"storage_type = {_format_value(column.storage_type)}"
            )
        if column.logical_type is not None:
            lines.append(
                f"logical_type = {_format_value(column.logical_type)}"
            )
        lines.append(f"nullable = {_format_value(column.nullable)}")
        if column.unique:
            lines.append("unique = true")
        if column.allowed_values is not None:
            lines.append(
                "allowed_values = "
                f"{_format_value(list(column.allowed_values))}"
            )
        if column.min_value is not None:
            lines.append(f"min = {_format_value(column.min_value)}")
        if column.max_value is not None:
            lines.append(f"max = {_format_value(column.max_value)}")
        if column.regex is not None:
            lines.append(f"regex = {_format_value(column.regex)}")

    for rule in model.rules:
        lines.extend(["", "[[rules]]"])
        for name, value in rule.to_dict().items():
            lines.append(f"{name} = {_format_value(value)}")

    text = "\n".join(lines) + "\n"
    parse_contract(tomllib.loads(text))
    return text


def export_schema_contract(
    dataset: Dataset,
    input_filename: str | Path,
    output_path: str | Path,
    *,
    overwrite: bool = False,
) -> Path:
    """Write a deterministic starter contract with safe output handling."""

    input_path = Path(input_filename)
    target = Path(output_path)
    extension = target.suffix.lower()
    if extension not in CONTRACT_EXTENSIONS:
        raise ContractError(
            f"Unsupported schema contract format: {extension or '(none)'}",
            suggestion="Use .toml.",
        )
    if target.resolve(strict=False) == input_path.resolve(strict=False):
        raise OutputPathError(
            f"Schema contract path would replace the input file: {target}",
            suggestion="Choose a different schema contract output path.",
        )
    _validate_output_path(target, overwrite=overwrite)

    contract = build_schema_contract(dataset, input_path)
    text = contract_to_toml(contract)
    try:
        target.write_text(text, encoding="utf-8", newline="\n")
    except OSError as exc:
        raise ContractError(
            f"Could not write schema contract: {target}. {exc}"
        ) from exc
    return target


def _validate_output_path(target: Path, *, overwrite: bool) -> None:
    parent = target.parent
    if parent != Path(".") and not parent.exists():
        raise OutputPathError(
            f"Parent folder does not exist: {parent}",
            suggestion="Create the folder first.",
        )
    if parent.exists() and not parent.is_dir():
        raise OutputPathError(
            f"Parent path is not a folder: {parent}",
            suggestion="Choose a contract path whose parent is a folder.",
        )
    if target.exists() and not target.is_file():
        raise OutputPathError(
            f"Schema contract output path is not a file: {target}",
            suggestion="Choose a TOML file path.",
        )
    if target.exists() and not overwrite:
        raise OutputPathError(
            f"Schema contract already exists: {target}",
            suggestion=(
                "Use --overwrite-contract to replace it, or choose a "
                "different path."
            ),
        )


def _format_value(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_format_value(item) for item in value) + "]"
    raise ContractError(
        "Schema contract error: cannot write TOML value of type "
        f"{type(value).__name__}."
    )


def _optional_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None
